HomebrewDesigner.UI/Controllers/CalculatorController.cs
using HomebrewDesigner.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HomebrewDesigner.Controllers;

[Route("[controller]/[action]")]
public class CalculatorController : Controller
{
    // GET
    [AllowAnonymous]
    public IActionResult Calculator()
    {
        CalculatorVM calc = new CalculatorVM();

        calc.OG = 1.050;
        calc.FG = 1.010;
        calc.ABV = Math.Round((calc.OG - calc.FG) * 131.25, 1);
        
        
        return View(calc);
    }
    
    [HttpPost]
    [AllowAnonymous]
    public IActionResult Calculator(CalculatorVM calc)
    {
        calc.ABV = Math.Round((calc.OG - calc.FG) * 131.25, 1);

        if (ModelState.IsValid)
        {
            return View(calc);
        }
        
        return View(calc);
        
    }
}

HomebrewDesigner.UI/Views/Shared/_Layout.cshtml
@using F1FanSite.ViewModels
@using HomebrewDesigner.Core.Services
@using Microsoft.AspNetCore.Mvc.TagHelpers
@{
    // use current controller or area to determine if tab is active
    var current = ViewContext.RouteData.Values["area"]?.ToString() ??
                  ViewContext.RouteData.Values["controller"]!.ToString()!;

    // use current action to determine active tab for register and change password tabs
    var action = ViewContext.RouteData.Values["action"]?.ToString().ToLower();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MVC_Homebrew_Recipe_Designer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" href="~/images/pale.png" type="image/png">
    <link href="https://fonts.googleapis.com/css2?family=Asap+Condensed:ital,wght@0,300;0,400;0,700;1,300&display=swap" rel="stylesheet">
</head>
<body >
<header>
    <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark mb-3 pt-4 pb-4 ">
        <div class="container-fluid">
            <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Home">
                <img class="nav-logo" src="~/images/hop.png"/>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse text-center" id="navbarNav">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light @Nav.Active(new string[] { "recipes", "editrecipe", "addfermentables", "addhops", "addrecipe", "viewrecipe", "deleterecipe" }, action)" asp-area="" asp-controller="Recipe" asp-action="Recipes">Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light @Nav.Active(new string[] { "hops", "edithop", "addhop" }, action)" asp-area="" asp-controller="Ingredient" asp-action="Hops">Hops</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light @Nav.Active(new string[] { "fermentables", "editfermentable", "addfermentable" }, action)" asp-area="" asp-controller="Ingredient" asp-action="Fermentables">Fermentables</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light @Nav.Active(new string[] { "yeast", "edityeast", "addyeast" }, action)" asp-area="" asp-controller="Ingredient" asp-action="Yeast">Yeast</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light @Nav.Active(new string[] { "calculator" }, action)" asp-area="" asp-controller="Calculator" asp-action="Calculator">ABV-Calculator</a>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item text-white">

                            <a class="text-white nav-link @Nav.Active(new string[] { "index", "add", "edit" }, action)" asp-action="Index" asp-controller="Admin" asp-area="">Admin</a>

                        </li>
                    }
                </ul>
                <div class="container text-end text-main col-4" id="userInfo">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div id="userDiv">
                            <div>
                                <span >Hello, @User.Identity.Name!</span> |<a asp-action="Logout" asp-controller="Account" class=" mx-2 mt-2 text-decoration-underline text-main">Logout</a>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div id="userDiv">
                            <a asp-controller="Account" asp-action="Login" class="mx-2 mt-2 text-light @Nav.Active(new string[] { "login" }, action)">Login</a> | <a asp-action="Register" asp-controller="Account" class=" mx-2 mt-2  text-light @Nav.Active(new string[] { "register" }, action)">Register</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer">
    <div class="container text-center text-main">
        @DateTime.Now.Year - MVC Homebrew Recipe Designer
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script type="module" src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>